version: '3.8'
services:
  tankbuch:
    image: ghcr.io/tech-n1c/tankbuch:latest
    container_name: tankbuch-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - tankbuch_public:/app/public

  db:
    image: postgres:16-alpine
    container_name: tankbuch-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  tankbuch_public:
